### ISSUE TITLE
missing dependencies for @dhcode/openapi-viewer

### ISSUE THREAD

**Issue by leemerlas** [dhcode/openapi-ui#10]
I was following the instructions on how to use the OpenApi Angular component, and installed all the missing dependencies, but this error keeps showing when trying to run my Angular app:

```
ERROR in The target entry-point "@dhcode/openapi-viewer" has missing dependencies:
 - swagger-client/browser/index
```

I uninstalled and re-installed the swagger-client package and still the same result. Is this a known bug?

**Comment by dhcode** [comment]
Thank you for reporting. I will check it out tonight.

**Comment by dhcode** [comment]
I updated the swagger-client dependency and fixed the not working import.
You just need the @angular/cdk as peer dependency, everything else should be installed automatically.
New version is now on NPM: @dhcode/openapi-viewer@0.1.1

There are still warning about brace and ajv. For brace I'm thing about replaceing that dependency with codemirror. ajv I don't know. But it should still work now.

**Comment by leemerlas** [comment]
Thanks! I'll try it out now
