### ISSUE TITLE
NPM release

### ISSUE THREAD

**Issue by jayvdb** [dhcode/openapi-ui#4]
Any chance you could start doing releases of this onto npmjs?

Unfortunately https://www.npmjs.com/package/openapi-ui is taken, and is hosted at https://github.com/rijx/openapi-ui . 

Also it would be great if the angular deps were moved to peerDeps, etc.

Also maybe link to https://github.com/Orange-OpenSource/angular-swagger-ui on the README for a similar project for anyone still using AngularJS.

**Comment by dhcode** [comment]
Two parts of this project are released to npmjs:
https://www.npmjs.com/package/@dhcode/openapi-viewer-element (0 dependencies webcomponent bundle)
https://www.npmjs.com/package/@dhcode/openapi-viewer (Anular library)

**Comment by jayvdb** [comment]
Nice. Sorry I didnt notice that.
Looks great.

**Comment by dhcode** [comment]
How would I refer to them via package.json?
I published now a new version, with a README, that contains a better usage example.
https://www.npmjs.com/package/@dhcode/openapi-viewer-element
